// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: api_keys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, label, key_hash, scopes, active, last_used_at, created_at, expires_at, client_id FROM api_keys WHERE key_hash = $1 AND active = TRUE
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.KeyHash,
		&i.Scopes,
		&i.Active,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClientID,
	)
	return i, err
}

const insertApiKey = `-- name: InsertApiKey :one
INSERT INTO api_keys (id, label, key_hash, scopes, active, expires_at, client_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, label, key_hash, scopes, active, last_used_at, created_at, expires_at, client_id
`

type InsertApiKeyParams struct {
	ID        pgtype.UUID
	Label     string
	KeyHash   string
	Scopes    []string
	Active    bool
	ExpiresAt pgtype.Timestamptz
	ClientID  pgtype.UUID
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertApiKey,
		arg.ID,
		arg.Label,
		arg.KeyHash,
		arg.Scopes,
		arg.Active,
		arg.ExpiresAt,
		arg.ClientID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.KeyHash,
		&i.Scopes,
		&i.Active,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClientID,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, label, key_hash, scopes, active, last_used_at, created_at, expires_at, client_id FROM api_keys ORDER BY created_at DESC
`

func (q *Queries) ListApiKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.KeyHash,
			&i.Scopes,
			&i.Active,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByClient = `-- name: ListApiKeysByClient :many
SELECT id, label, key_hash, scopes, active, last_used_at, created_at, expires_at, client_id FROM api_keys WHERE client_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByClient(ctx context.Context, clientID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.KeyHash,
			&i.Scopes,
			&i.Active,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys SET active = FALSE WHERE id = $1
`

func (q *Queries) RevokeApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeApiKey, id)
	return err
}

const touchApiKey = `-- name: TouchApiKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchApiKey, id)
	return err
}
