// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_connections.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBankConnections = `-- name: CountActiveBankConnections :one
SELECT count(*) FROM bank_connections WHERE client_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveBankConnections(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBankConnections, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBankConnection = `-- name: DeleteBankConnection :exec
DELETE FROM bank_connections WHERE id = $1 AND client_id = $2
`

type DeleteBankConnectionParams struct {
	ID       pgtype.UUID
	ClientID pgtype.UUID
}

func (q *Queries) DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteBankConnection, arg.ID, arg.ClientID)
	return err
}

const getBankConnection = `-- name: GetBankConnection :one
SELECT id, client_id, bank_code, bank_name, auth_method, credentials_enc, certificate_enc, private_key_enc, nonce, sftp_host, sftp_user, sftp_key_enc, sftp_remessa_dir, sftp_retorno_dir, status, validation_attempts, last_validation_error, last_validated_at, expires_at, created_at, updated_at FROM bank_connections WHERE id = $1 AND client_id = $2
`

type GetBankConnectionParams struct {
	ID       pgtype.UUID
	ClientID pgtype.UUID
}

func (q *Queries) GetBankConnection(ctx context.Context, arg GetBankConnectionParams) (BankConnection, error) {
	row := q.db.QueryRow(ctx, getBankConnection, arg.ID, arg.ClientID)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BankCode,
		&i.BankName,
		&i.AuthMethod,
		&i.CredentialsEnc,
		&i.CertificateEnc,
		&i.PrivateKeyEnc,
		&i.Nonce,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyEnc,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Status,
		&i.ValidationAttempts,
		&i.LastValidationError,
		&i.LastValidatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankConnectionByBank = `-- name: GetBankConnectionByBank :one
SELECT id, client_id, bank_code, bank_name, auth_method, credentials_enc, certificate_enc, private_key_enc, nonce, sftp_host, sftp_user, sftp_key_enc, sftp_remessa_dir, sftp_retorno_dir, status, validation_attempts, last_validation_error, last_validated_at, expires_at, created_at, updated_at FROM bank_connections WHERE client_id = $1 AND bank_code = $2
`

type GetBankConnectionByBankParams struct {
	ClientID pgtype.UUID
	BankCode string
}

func (q *Queries) GetBankConnectionByBank(ctx context.Context, arg GetBankConnectionByBankParams) (BankConnection, error) {
	row := q.db.QueryRow(ctx, getBankConnectionByBank, arg.ClientID, arg.BankCode)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BankCode,
		&i.BankName,
		&i.AuthMethod,
		&i.CredentialsEnc,
		&i.CertificateEnc,
		&i.PrivateKeyEnc,
		&i.Nonce,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyEnc,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Status,
		&i.ValidationAttempts,
		&i.LastValidationError,
		&i.LastValidatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBankConnection = `-- name: InsertBankConnection :one
INSERT INTO bank_connections (
    id, client_id, bank_code, bank_name, auth_method,
    credentials_enc, certificate_enc, private_key_enc, nonce,
    sftp_host, sftp_user, sftp_key_enc, sftp_remessa_dir, sftp_retorno_dir,
    status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, client_id, bank_code, bank_name, auth_method, credentials_enc, certificate_enc, private_key_enc, nonce, sftp_host, sftp_user, sftp_key_enc, sftp_remessa_dir, sftp_retorno_dir, status, validation_attempts, last_validation_error, last_validated_at, expires_at, created_at, updated_at
`

type InsertBankConnectionParams struct {
	ID             pgtype.UUID
	ClientID       pgtype.UUID
	BankCode       string
	BankName       string
	AuthMethod     string
	CredentialsEnc []byte
	CertificateEnc []byte
	PrivateKeyEnc  []byte
	Nonce          []byte
	SftpHost       pgtype.Text
	SftpUser       pgtype.Text
	SftpKeyEnc     []byte
	SftpRemessaDir pgtype.Text
	SftpRetornoDir pgtype.Text
	Status         string
}

func (q *Queries) InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error) {
	row := q.db.QueryRow(ctx, insertBankConnection,
		arg.ID,
		arg.ClientID,
		arg.BankCode,
		arg.BankName,
		arg.AuthMethod,
		arg.CredentialsEnc,
		arg.CertificateEnc,
		arg.PrivateKeyEnc,
		arg.Nonce,
		arg.SftpHost,
		arg.SftpUser,
		arg.SftpKeyEnc,
		arg.SftpRemessaDir,
		arg.SftpRetornoDir,
		arg.Status,
	)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BankCode,
		&i.BankName,
		&i.AuthMethod,
		&i.CredentialsEnc,
		&i.CertificateEnc,
		&i.PrivateKeyEnc,
		&i.Nonce,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyEnc,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Status,
		&i.ValidationAttempts,
		&i.LastValidationError,
		&i.LastValidatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankConnections = `-- name: ListBankConnections :many
SELECT id, client_id, bank_code, bank_name, auth_method, credentials_enc, certificate_enc, private_key_enc, nonce, sftp_host, sftp_user, sftp_key_enc, sftp_remessa_dir, sftp_retorno_dir, status, validation_attempts, last_validation_error, last_validated_at, expires_at, created_at, updated_at FROM bank_connections WHERE client_id = $1 ORDER BY bank_name
`

func (q *Queries) ListBankConnections(ctx context.Context, clientID pgtype.UUID) ([]BankConnection, error) {
	rows, err := q.db.Query(ctx, listBankConnections, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankConnection{}
	for rows.Next() {
		var i BankConnection
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.BankCode,
			&i.BankName,
			&i.AuthMethod,
			&i.CredentialsEnc,
			&i.CertificateEnc,
			&i.PrivateKeyEnc,
			&i.Nonce,
			&i.SftpHost,
			&i.SftpUser,
			&i.SftpKeyEnc,
			&i.SftpRemessaDir,
			&i.SftpRetornoDir,
			&i.Status,
			&i.ValidationAttempts,
			&i.LastValidationError,
			&i.LastValidatedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankConnectionCredentials = `-- name: UpdateBankConnectionCredentials :exec
UPDATE bank_connections SET
    credentials_enc = $3, certificate_enc = $4, private_key_enc = $5, nonce = $6,
    sftp_host = $7, sftp_user = $8, sftp_key_enc = $9, sftp_remessa_dir = $10, sftp_retorno_dir = $11,
    updated_at = now()
WHERE id = $1 AND client_id = $2
`

type UpdateBankConnectionCredentialsParams struct {
	ID             pgtype.UUID
	ClientID       pgtype.UUID
	CredentialsEnc []byte
	CertificateEnc []byte
	PrivateKeyEnc  []byte
	Nonce          []byte
	SftpHost       pgtype.Text
	SftpUser       pgtype.Text
	SftpKeyEnc     []byte
	SftpRemessaDir pgtype.Text
	SftpRetornoDir pgtype.Text
}

func (q *Queries) UpdateBankConnectionCredentials(ctx context.Context, arg UpdateBankConnectionCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateBankConnectionCredentials,
		arg.ID,
		arg.ClientID,
		arg.CredentialsEnc,
		arg.CertificateEnc,
		arg.PrivateKeyEnc,
		arg.Nonce,
		arg.SftpHost,
		arg.SftpUser,
		arg.SftpKeyEnc,
		arg.SftpRemessaDir,
		arg.SftpRetornoDir,
	)
	return err
}

const updateBankConnectionStatus = `-- name: UpdateBankConnectionStatus :exec
UPDATE bank_connections SET
    status = $3,
    validation_attempts = $4,
    last_validation_error = $5,
    last_validated_at = CASE WHEN $3 = 'active' THEN now() ELSE last_validated_at END,
    updated_at = now()
WHERE id = $1 AND client_id = $2
`

type UpdateBankConnectionStatusParams struct {
	ID                  pgtype.UUID
	ClientID            pgtype.UUID
	Status              string
	ValidationAttempts  int32
	LastValidationError pgtype.Text
}

func (q *Queries) UpdateBankConnectionStatus(ctx context.Context, arg UpdateBankConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateBankConnectionStatus,
		arg.ID,
		arg.ClientID,
		arg.Status,
		arg.ValidationAttempts,
		arg.LastValidationError,
	)
	return err
}
