// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: bank_certificates.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBankCertificate = `-- name: DeleteBankCertificate :exec
DELETE FROM bank_certificates WHERE id = $1
`

func (q *Queries) DeleteBankCertificate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBankCertificate, id)
	return err
}

const getBankCertificate = `-- name: GetBankCertificate :one
SELECT id, bank_code, purpose, cert_pem_enc, key_pem_enc, nonce, expires_at, created_at FROM bank_certificates WHERE id = $1
`

func (q *Queries) GetBankCertificate(ctx context.Context, id pgtype.UUID) (BankCertificate, error) {
	row := q.db.QueryRow(ctx, getBankCertificate, id)
	var i BankCertificate
	err := row.Scan(
		&i.ID,
		&i.BankCode,
		&i.Purpose,
		&i.CertPemEnc,
		&i.KeyPemEnc,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBankCertificate = `-- name: InsertBankCertificate :one
INSERT INTO bank_certificates (id, bank_code, purpose, cert_pem_enc, key_pem_enc, nonce, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bank_code, purpose, cert_pem_enc, key_pem_enc, nonce, expires_at, created_at
`

type InsertBankCertificateParams struct {
	ID         pgtype.UUID
	BankCode   string
	Purpose    string
	CertPemEnc []byte
	KeyPemEnc  []byte
	Nonce      []byte
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) InsertBankCertificate(ctx context.Context, arg InsertBankCertificateParams) (BankCertificate, error) {
	row := q.db.QueryRow(ctx, insertBankCertificate,
		arg.ID,
		arg.BankCode,
		arg.Purpose,
		arg.CertPemEnc,
		arg.KeyPemEnc,
		arg.Nonce,
		arg.ExpiresAt,
	)
	var i BankCertificate
	err := row.Scan(
		&i.ID,
		&i.BankCode,
		&i.Purpose,
		&i.CertPemEnc,
		&i.KeyPemEnc,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBankCertificatesByBank = `-- name: ListBankCertificatesByBank :many
SELECT id, bank_code, purpose, cert_pem_enc, key_pem_enc, nonce, expires_at, created_at FROM bank_certificates
WHERE bank_code = $1 AND purpose = $2
ORDER BY expires_at DESC
`

type ListBankCertificatesByBankParams struct {
	BankCode string
	Purpose  string
}

func (q *Queries) ListBankCertificatesByBank(ctx context.Context, arg ListBankCertificatesByBankParams) ([]BankCertificate, error) {
	rows, err := q.db.Query(ctx, listBankCertificatesByBank, arg.BankCode, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankCertificate{}
	for rows.Next() {
		var i BankCertificate
		if err := rows.Scan(
			&i.ID,
			&i.BankCode,
			&i.Purpose,
			&i.CertPemEnc,
			&i.KeyPemEnc,
			&i.Nonce,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
