// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: beneficiaries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBeneficiary = `-- name: GetBeneficiary :one
SELECT id, kind, legal_name, trade_name, document_type, document_number, email, phone, tags, default_payment_method, notes, active, created_at, updated_at, client_id FROM beneficiaries WHERE id = $1
`

func (q *Queries) GetBeneficiary(ctx context.Context, id pgtype.UUID) (Beneficiary, error) {
	row := q.db.QueryRow(ctx, getBeneficiary, id)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.LegalName,
		&i.TradeName,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Email,
		&i.Phone,
		&i.Tags,
		&i.DefaultPaymentMethod,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
	)
	return i, err
}

const getBeneficiaryByDocument = `-- name: GetBeneficiaryByDocument :one
SELECT id, kind, legal_name, trade_name, document_type, document_number, email, phone, tags, default_payment_method, notes, active, created_at, updated_at, client_id FROM beneficiaries WHERE document_number = $1
`

func (q *Queries) GetBeneficiaryByDocument(ctx context.Context, documentNumber string) (Beneficiary, error) {
	row := q.db.QueryRow(ctx, getBeneficiaryByDocument, documentNumber)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.LegalName,
		&i.TradeName,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Email,
		&i.Phone,
		&i.Tags,
		&i.DefaultPaymentMethod,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
	)
	return i, err
}

const insertBeneficiary = `-- name: InsertBeneficiary :one
INSERT INTO beneficiaries (
    id, kind, legal_name, trade_name, document_type, document_number,
    email, phone, tags, default_payment_method, notes, active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, kind, legal_name, trade_name, document_type, document_number, email, phone, tags, default_payment_method, notes, active, created_at, updated_at, client_id
`

type InsertBeneficiaryParams struct {
	ID                   pgtype.UUID
	Kind                 string
	LegalName            string
	TradeName            pgtype.Text
	DocumentType         string
	DocumentNumber       string
	Email                pgtype.Text
	Phone                pgtype.Text
	Tags                 []string
	DefaultPaymentMethod pgtype.Text
	Notes                pgtype.Text
	Active               bool
}

func (q *Queries) InsertBeneficiary(ctx context.Context, arg InsertBeneficiaryParams) (Beneficiary, error) {
	row := q.db.QueryRow(ctx, insertBeneficiary,
		arg.ID,
		arg.Kind,
		arg.LegalName,
		arg.TradeName,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Email,
		arg.Phone,
		arg.Tags,
		arg.DefaultPaymentMethod,
		arg.Notes,
		arg.Active,
	)
	var i Beneficiary
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.LegalName,
		&i.TradeName,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Email,
		&i.Phone,
		&i.Tags,
		&i.DefaultPaymentMethod,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
	)
	return i, err
}

const insertBeneficiaryBankAccount = `-- name: InsertBeneficiaryBankAccount :one
INSERT INTO beneficiary_bank_accounts (
    id, beneficiary_id, bank_code, agency, account_number, account_digit,
    account_type, label, active, verified_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, beneficiary_id, bank_code, agency, account_number, account_digit, account_type, label, active, verified_at, created_at
`

type InsertBeneficiaryBankAccountParams struct {
	ID            pgtype.UUID
	BeneficiaryID pgtype.UUID
	BankCode      string
	Agency        string
	AccountNumber string
	AccountDigit  string
	AccountType   string
	Label         pgtype.Text
	Active        bool
	VerifiedAt    pgtype.Timestamptz
}

func (q *Queries) InsertBeneficiaryBankAccount(ctx context.Context, arg InsertBeneficiaryBankAccountParams) (BeneficiaryBankAccount, error) {
	row := q.db.QueryRow(ctx, insertBeneficiaryBankAccount,
		arg.ID,
		arg.BeneficiaryID,
		arg.BankCode,
		arg.Agency,
		arg.AccountNumber,
		arg.AccountDigit,
		arg.AccountType,
		arg.Label,
		arg.Active,
		arg.VerifiedAt,
	)
	var i BeneficiaryBankAccount
	err := row.Scan(
		&i.ID,
		&i.BeneficiaryID,
		&i.BankCode,
		&i.Agency,
		&i.AccountNumber,
		&i.AccountDigit,
		&i.AccountType,
		&i.Label,
		&i.Active,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBeneficiaryPixKey = `-- name: InsertBeneficiaryPixKey :one
INSERT INTO beneficiary_pix_keys (id, beneficiary_id, key_type, key_value, label, active, verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, beneficiary_id, key_type, key_value, label, active, verified_at, created_at
`

type InsertBeneficiaryPixKeyParams struct {
	ID            pgtype.UUID
	BeneficiaryID pgtype.UUID
	KeyType       string
	KeyValue      string
	Label         pgtype.Text
	Active        bool
	VerifiedAt    pgtype.Timestamptz
}

func (q *Queries) InsertBeneficiaryPixKey(ctx context.Context, arg InsertBeneficiaryPixKeyParams) (BeneficiaryPixKey, error) {
	row := q.db.QueryRow(ctx, insertBeneficiaryPixKey,
		arg.ID,
		arg.BeneficiaryID,
		arg.KeyType,
		arg.KeyValue,
		arg.Label,
		arg.Active,
		arg.VerifiedAt,
	)
	var i BeneficiaryPixKey
	err := row.Scan(
		&i.ID,
		&i.BeneficiaryID,
		&i.KeyType,
		&i.KeyValue,
		&i.Label,
		&i.Active,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBeneficiaries = `-- name: ListBeneficiaries :many
SELECT id, kind, legal_name, trade_name, document_type, document_number, email, phone, tags, default_payment_method, notes, active, created_at, updated_at, client_id FROM beneficiaries
WHERE active = TRUE
ORDER BY legal_name
LIMIT $1 OFFSET $2
`

type ListBeneficiariesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBeneficiaries(ctx context.Context, arg ListBeneficiariesParams) ([]Beneficiary, error) {
	rows, err := q.db.Query(ctx, listBeneficiaries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Beneficiary{}
	for rows.Next() {
		var i Beneficiary
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.LegalName,
			&i.TradeName,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Email,
			&i.Phone,
			&i.Tags,
			&i.DefaultPaymentMethod,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeneficiaryBankAccounts = `-- name: ListBeneficiaryBankAccounts :many
SELECT id, beneficiary_id, bank_code, agency, account_number, account_digit, account_type, label, active, verified_at, created_at FROM beneficiary_bank_accounts
WHERE beneficiary_id = $1 AND active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListBeneficiaryBankAccounts(ctx context.Context, beneficiaryID pgtype.UUID) ([]BeneficiaryBankAccount, error) {
	rows, err := q.db.Query(ctx, listBeneficiaryBankAccounts, beneficiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BeneficiaryBankAccount{}
	for rows.Next() {
		var i BeneficiaryBankAccount
		if err := rows.Scan(
			&i.ID,
			&i.BeneficiaryID,
			&i.BankCode,
			&i.Agency,
			&i.AccountNumber,
			&i.AccountDigit,
			&i.AccountType,
			&i.Label,
			&i.Active,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeneficiaryPixKeys = `-- name: ListBeneficiaryPixKeys :many
SELECT id, beneficiary_id, key_type, key_value, label, active, verified_at, created_at FROM beneficiary_pix_keys
WHERE beneficiary_id = $1 AND active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListBeneficiaryPixKeys(ctx context.Context, beneficiaryID pgtype.UUID) ([]BeneficiaryPixKey, error) {
	rows, err := q.db.Query(ctx, listBeneficiaryPixKeys, beneficiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BeneficiaryPixKey{}
	for rows.Next() {
		var i BeneficiaryPixKey
		if err := rows.Scan(
			&i.ID,
			&i.BeneficiaryID,
			&i.KeyType,
			&i.KeyValue,
			&i.Label,
			&i.Active,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
