// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: blacklist.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBlacklist = `-- name: CheckBlacklist :many
SELECT id, client_id, document_number, reason, active, created_by, created_at FROM blacklist_entries
WHERE document_number = $1 AND active = TRUE
  AND (client_id IS NULL OR client_id = $2)
`

type CheckBlacklistParams struct {
	DocumentNumber string
	ClientID       pgtype.UUID
}

func (q *Queries) CheckBlacklist(ctx context.Context, arg CheckBlacklistParams) ([]BlacklistEntry, error) {
	rows, err := q.db.Query(ctx, checkBlacklist, arg.DocumentNumber, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlacklistEntry{}
	for rows.Next() {
		var i BlacklistEntry
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DocumentNumber,
			&i.Reason,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateBlacklistEntry = `-- name: DeactivateBlacklistEntry :exec
UPDATE blacklist_entries SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateBlacklistEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateBlacklistEntry, id)
	return err
}

const insertBlacklistEntry = `-- name: InsertBlacklistEntry :one
INSERT INTO blacklist_entries (id, client_id, document_number, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, document_number, reason, active, created_by, created_at
`

type InsertBlacklistEntryParams struct {
	ID             pgtype.UUID
	ClientID       pgtype.UUID
	DocumentNumber string
	Reason         string
	CreatedBy      string
}

func (q *Queries) InsertBlacklistEntry(ctx context.Context, arg InsertBlacklistEntryParams) (BlacklistEntry, error) {
	row := q.db.QueryRow(ctx, insertBlacklistEntry,
		arg.ID,
		arg.ClientID,
		arg.DocumentNumber,
		arg.Reason,
		arg.CreatedBy,
	)
	var i BlacklistEntry
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DocumentNumber,
		&i.Reason,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listBlacklistByClient = `-- name: ListBlacklistByClient :many
SELECT id, client_id, document_number, reason, active, created_by, created_at FROM blacklist_entries
WHERE (client_id IS NULL OR client_id = $1) AND active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListBlacklistByClient(ctx context.Context, clientID pgtype.UUID) ([]BlacklistEntry, error) {
	rows, err := q.db.Query(ctx, listBlacklistByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlacklistEntry{}
	for rows.Next() {
		var i BlacklistEntry
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DocumentNumber,
			&i.Reason,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
