// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: clients.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClient = `-- name: GetClient :one
SELECT id, name, document_type, document_number, active, webhook_url, webhook_secret, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Active,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByDocument = `-- name: GetClientByDocument :one
SELECT id, name, document_type, document_number, active, webhook_url, webhook_secret, created_at, updated_at FROM clients WHERE document_number = $1
`

func (q *Queries) GetClientByDocument(ctx context.Context, documentNumber string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByDocument, documentNumber)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Active,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClient = `-- name: InsertClient :one
INSERT INTO clients (id, name, document_type, document_number, active, webhook_url, webhook_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, document_type, document_number, active, webhook_url, webhook_secret, created_at, updated_at
`

type InsertClientParams struct {
	ID             pgtype.UUID
	Name           string
	DocumentType   string
	DocumentNumber string
	Active         bool
	WebhookUrl     pgtype.Text
	WebhookSecret  pgtype.Text
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, insertClient,
		arg.ID,
		arg.Name,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Active,
		arg.WebhookUrl,
		arg.WebhookSecret,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Active,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, document_type, document_number, active, webhook_url, webhook_secret, created_at, updated_at FROM clients WHERE active = TRUE ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Active,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClientActive = `-- name: SetClientActive :exec
UPDATE clients SET active = $2, updated_at = now() WHERE id = $1
`

type SetClientActiveParams struct {
	ID     pgtype.UUID
	Active bool
}

func (q *Queries) SetClientActive(ctx context.Context, arg SetClientActiveParams) error {
	_, err := q.db.Exec(ctx, setClientActive, arg.ID, arg.Active)
	return err
}

const updateClientWebhook = `-- name: UpdateClientWebhook :exec
UPDATE clients SET webhook_url = $2, webhook_secret = $3, updated_at = now() WHERE id = $1
`

type UpdateClientWebhookParams struct {
	ID            pgtype.UUID
	WebhookUrl    pgtype.Text
	WebhookSecret pgtype.Text
}

func (q *Queries) UpdateClientWebhook(ctx context.Context, arg UpdateClientWebhookParams) error {
	_, err := q.db.Exec(ctx, updateClientWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecret)
	return err
}
