// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: client_limits.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClientLimit = `-- name: GetClientLimit :one
SELECT id, client_id, daily_limit_cents, monthly_limit_cents, max_single_cents, require_approval_above, active, created_at, updated_at FROM client_limits WHERE client_id = $1 AND active = TRUE
`

func (q *Queries) GetClientLimit(ctx context.Context, clientID pgtype.UUID) (ClientLimit, error) {
	row := q.db.QueryRow(ctx, getClientLimit, clientID)
	var i ClientLimit
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DailyLimitCents,
		&i.MonthlyLimitCents,
		&i.MaxSingleCents,
		&i.RequireApprovalAbove,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClientLimit = `-- name: InsertClientLimit :one
INSERT INTO client_limits (id, client_id, daily_limit_cents, monthly_limit_cents, max_single_cents, require_approval_above)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, daily_limit_cents, monthly_limit_cents, max_single_cents, require_approval_above, active, created_at, updated_at
`

type InsertClientLimitParams struct {
	ID                   pgtype.UUID
	ClientID             pgtype.UUID
	DailyLimitCents      int64
	MonthlyLimitCents    int64
	MaxSingleCents       int64
	RequireApprovalAbove int64
}

func (q *Queries) InsertClientLimit(ctx context.Context, arg InsertClientLimitParams) (ClientLimit, error) {
	row := q.db.QueryRow(ctx, insertClientLimit,
		arg.ID,
		arg.ClientID,
		arg.DailyLimitCents,
		arg.MonthlyLimitCents,
		arg.MaxSingleCents,
		arg.RequireApprovalAbove,
	)
	var i ClientLimit
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DailyLimitCents,
		&i.MonthlyLimitCents,
		&i.MaxSingleCents,
		&i.RequireApprovalAbove,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumPaymentsMonthByClient = `-- name: SumPaymentsMonthByClient :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS total
FROM payments
WHERE client_id = $1
  AND created_at >= date_trunc('month', CURRENT_DATE)
  AND status NOT IN ('REJECTED', 'CANCELED', 'EXPIRED')
`

func (q *Queries) SumPaymentsMonthByClient(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPaymentsMonthByClient, clientID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPaymentsTodayByClient = `-- name: SumPaymentsTodayByClient :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS total
FROM payments
WHERE client_id = $1
  AND created_at >= CURRENT_DATE
  AND status NOT IN ('REJECTED', 'CANCELED', 'EXPIRED')
`

func (q *Queries) SumPaymentsTodayByClient(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPaymentsTodayByClient, clientID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateClientLimit = `-- name: UpdateClientLimit :exec
UPDATE client_limits
SET daily_limit_cents = $2, monthly_limit_cents = $3, max_single_cents = $4,
    require_approval_above = $5, updated_at = now()
WHERE client_id = $1
`

type UpdateClientLimitParams struct {
	ClientID             pgtype.UUID
	DailyLimitCents      int64
	MonthlyLimitCents    int64
	MaxSingleCents       int64
	RequireApprovalAbove int64
}

func (q *Queries) UpdateClientLimit(ctx context.Context, arg UpdateClientLimitParams) error {
	_, err := q.db.Exec(ctx, updateClientLimit,
		arg.ClientID,
		arg.DailyLimitCents,
		arg.MonthlyLimitCents,
		arg.MaxSingleCents,
		arg.RequireApprovalAbove,
	)
	return err
}
