// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cnab_files.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCnabFile = `-- name: GetCnabFile :one
SELECT id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at FROM cnab_files WHERE id = $1
`

func (q *Queries) GetCnabFile(ctx context.Context, id pgtype.UUID) (CnabFile, error) {
	row := q.db.QueryRow(ctx, getCnabFile, id)
	var i CnabFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BankCode,
		&i.LayoutVersion,
		&i.SequenceNumber,
		&i.Direction,
		&i.FilePath,
		&i.FileHash,
		&i.Status,
		&i.TotalItems,
		&i.GeneratedAt,
		&i.UploadedAt,
		&i.UploadAck,
		&i.ReturnedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getCnabFileByHash = `-- name: GetCnabFileByHash :one
SELECT id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at FROM cnab_files WHERE file_hash = $1
`

func (q *Queries) GetCnabFileByHash(ctx context.Context, fileHash string) (CnabFile, error) {
	row := q.db.QueryRow(ctx, getCnabFileByHash, fileHash)
	var i CnabFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BankCode,
		&i.LayoutVersion,
		&i.SequenceNumber,
		&i.Direction,
		&i.FilePath,
		&i.FileHash,
		&i.Status,
		&i.TotalItems,
		&i.GeneratedAt,
		&i.UploadedAt,
		&i.UploadAck,
		&i.ReturnedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertCnabFile = `-- name: InsertCnabFile :one
INSERT INTO cnab_files (
    id, run_id, bank_code, layout_version, sequence_number, direction,
    file_path, file_hash, status, total_items, generated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at
`

type InsertCnabFileParams struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	BankCode       string
	LayoutVersion  string
	SequenceNumber int32
	Direction      string
	FilePath       string
	FileHash       string
	Status         string
	TotalItems     int32
	GeneratedAt    pgtype.Timestamptz
}

func (q *Queries) InsertCnabFile(ctx context.Context, arg InsertCnabFileParams) (CnabFile, error) {
	row := q.db.QueryRow(ctx, insertCnabFile,
		arg.ID,
		arg.RunID,
		arg.BankCode,
		arg.LayoutVersion,
		arg.SequenceNumber,
		arg.Direction,
		arg.FilePath,
		arg.FileHash,
		arg.Status,
		arg.TotalItems,
		arg.GeneratedAt,
	)
	var i CnabFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BankCode,
		&i.LayoutVersion,
		&i.SequenceNumber,
		&i.Direction,
		&i.FilePath,
		&i.FileHash,
		&i.Status,
		&i.TotalItems,
		&i.GeneratedAt,
		&i.UploadedAt,
		&i.UploadAck,
		&i.ReturnedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listCnabFilesByRun = `-- name: ListCnabFilesByRun :many
SELECT id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at FROM cnab_files
WHERE run_id = $1
ORDER BY direction, sequence_number
`

func (q *Queries) ListCnabFilesByRun(ctx context.Context, runID pgtype.UUID) ([]CnabFile, error) {
	rows, err := q.db.Query(ctx, listCnabFilesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CnabFile{}
	for rows.Next() {
		var i CnabFile
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.BankCode,
			&i.LayoutVersion,
			&i.SequenceNumber,
			&i.Direction,
			&i.FilePath,
			&i.FileHash,
			&i.Status,
			&i.TotalItems,
			&i.GeneratedAt,
			&i.UploadedAt,
			&i.UploadAck,
			&i.ReturnedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCnabFilesByStatus = `-- name: ListCnabFilesByStatus :many
SELECT id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at FROM cnab_files WHERE status = $1 ORDER BY generated_at
`

func (q *Queries) ListCnabFilesByStatus(ctx context.Context, status string) ([]CnabFile, error) {
	rows, err := q.db.Query(ctx, listCnabFilesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CnabFile{}
	for rows.Next() {
		var i CnabFile
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.BankCode,
			&i.LayoutVersion,
			&i.SequenceNumber,
			&i.Direction,
			&i.FilePath,
			&i.FileHash,
			&i.Status,
			&i.TotalItems,
			&i.GeneratedAt,
			&i.UploadedAt,
			&i.UploadAck,
			&i.ReturnedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCnabFileStatus = `-- name: UpdateCnabFileStatus :one
UPDATE cnab_files
SET status = $2,
    uploaded_at = COALESCE($3, uploaded_at),
    upload_ack = COALESCE($4, upload_ack),
    returned_at = COALESCE($5, returned_at),
    processed_at = COALESCE($6, processed_at)
WHERE id = $1
RETURNING id, run_id, bank_code, layout_version, sequence_number, direction, file_path, file_hash, status, total_items, generated_at, uploaded_at, upload_ack, returned_at, processed_at
`

type UpdateCnabFileStatusParams struct {
	ID          pgtype.UUID
	Status      string
	UploadedAt  pgtype.Timestamptz
	UploadAck   pgtype.Text
	ReturnedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) UpdateCnabFileStatus(ctx context.Context, arg UpdateCnabFileStatusParams) (CnabFile, error) {
	row := q.db.QueryRow(ctx, updateCnabFileStatus,
		arg.ID,
		arg.Status,
		arg.UploadedAt,
		arg.UploadAck,
		arg.ReturnedAt,
		arg.ProcessedAt,
	)
	var i CnabFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BankCode,
		&i.LayoutVersion,
		&i.SequenceNumber,
		&i.Direction,
		&i.FilePath,
		&i.FileHash,
		&i.Status,
		&i.TotalItems,
		&i.GeneratedAt,
		&i.UploadedAt,
		&i.UploadAck,
		&i.ReturnedAt,
		&i.ProcessedAt,
	)
	return i, err
}
