// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: dummy.sql

package dbgen

import (
	"context"
)

const getSchemaMetadataValue = `-- name: GetSchemaMetadataValue :one
SELECT value FROM schema_metadata WHERE key = $1
`

func (q *Queries) GetSchemaMetadataValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSchemaMetadataValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
