// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: duplicate_rules.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findDuplicatePayments = `-- name: FindDuplicatePayments :many
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments
WHERE client_id = $1
  AND beneficiary_id = $2
  AND amount_cents = $3
  AND created_at > $4
  AND status NOT IN ('REJECTED', 'CANCELED', 'EXPIRED')
  AND id != $5
ORDER BY created_at DESC
LIMIT 5
`

type FindDuplicatePaymentsParams struct {
	ClientID      pgtype.UUID
	BeneficiaryID pgtype.UUID
	AmountCents   int64
	CreatedAt     pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) FindDuplicatePayments(ctx context.Context, arg FindDuplicatePaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, findDuplicatePayments,
		arg.ClientID,
		arg.BeneficiaryID,
		arg.AmountCents,
		arg.CreatedAt,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.PayerAccountID,
			&i.BeneficiaryID,
			&i.BeneficiarySnapshot,
			&i.PayeeMethod,
			&i.Payee,
			&i.Description,
			&i.ScheduledFor,
			&i.IdempotencyKey,
			&i.BankReference,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.RescheduledFrom,
			&i.RescheduledReason,
			&i.OperatorNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateRule = `-- name: GetDuplicateRule :one
SELECT id, client_id, window_hours, match_fields, action, active, created_at FROM duplicate_rules WHERE client_id = $1 AND active = TRUE
`

func (q *Queries) GetDuplicateRule(ctx context.Context, clientID pgtype.UUID) (DuplicateRule, error) {
	row := q.db.QueryRow(ctx, getDuplicateRule, clientID)
	var i DuplicateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.WindowHours,
		&i.MatchFields,
		&i.Action,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const insertDuplicateRule = `-- name: InsertDuplicateRule :one
INSERT INTO duplicate_rules (id, client_id, window_hours, match_fields, action)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, window_hours, match_fields, action, active, created_at
`

type InsertDuplicateRuleParams struct {
	ID          pgtype.UUID
	ClientID    pgtype.UUID
	WindowHours int32
	MatchFields []string
	Action      string
}

func (q *Queries) InsertDuplicateRule(ctx context.Context, arg InsertDuplicateRuleParams) (DuplicateRule, error) {
	row := q.db.QueryRow(ctx, insertDuplicateRule,
		arg.ID,
		arg.ClientID,
		arg.WindowHours,
		arg.MatchFields,
		arg.Action,
	)
	var i DuplicateRule
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.WindowHours,
		&i.MatchFields,
		&i.Action,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
