// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: idempotency_keys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, scope, request_hash, response_snapshot, status_code, created_at, expires_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseSnapshot,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (key, scope, request_hash, response_snapshot, status_code, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING key, scope, request_hash, response_snapshot, status_code, created_at, expires_at
`

type InsertIdempotencyKeyParams struct {
	Key              string
	Scope            string
	RequestHash      string
	ResponseSnapshot []byte
	StatusCode       int32
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.RequestHash,
		arg.ResponseSnapshot,
		arg.StatusCode,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseSnapshot,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
