// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMetadatum struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}
