// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payer_accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPayerAccount = `-- name: GetPayerAccount :one
SELECT id, bank_code, agency, account_number, account_digit, certificate_id, oauth_client_id, oauth_secret_ref, sftp_host, sftp_user, sftp_key_ref, sftp_remessa_dir, sftp_retorno_dir, label, active, created_at, updated_at FROM payer_accounts WHERE id = $1
`

func (q *Queries) GetPayerAccount(ctx context.Context, id pgtype.UUID) (PayerAccount, error) {
	row := q.db.QueryRow(ctx, getPayerAccount, id)
	var i PayerAccount
	err := row.Scan(
		&i.ID,
		&i.BankCode,
		&i.Agency,
		&i.AccountNumber,
		&i.AccountDigit,
		&i.CertificateID,
		&i.OauthClientID,
		&i.OauthSecretRef,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyRef,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayerAccountByLabel = `-- name: GetPayerAccountByLabel :one
SELECT id, bank_code, agency, account_number, account_digit, certificate_id, oauth_client_id, oauth_secret_ref, sftp_host, sftp_user, sftp_key_ref, sftp_remessa_dir, sftp_retorno_dir, label, active, created_at, updated_at FROM payer_accounts WHERE label = $1
`

func (q *Queries) GetPayerAccountByLabel(ctx context.Context, label string) (PayerAccount, error) {
	row := q.db.QueryRow(ctx, getPayerAccountByLabel, label)
	var i PayerAccount
	err := row.Scan(
		&i.ID,
		&i.BankCode,
		&i.Agency,
		&i.AccountNumber,
		&i.AccountDigit,
		&i.CertificateID,
		&i.OauthClientID,
		&i.OauthSecretRef,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyRef,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayerAccount = `-- name: InsertPayerAccount :one
INSERT INTO payer_accounts (
    id, bank_code, agency, account_number, account_digit,
    certificate_id, oauth_client_id, oauth_secret_ref,
    sftp_host, sftp_user, sftp_key_ref, sftp_remessa_dir, sftp_retorno_dir,
    label, active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, bank_code, agency, account_number, account_digit, certificate_id, oauth_client_id, oauth_secret_ref, sftp_host, sftp_user, sftp_key_ref, sftp_remessa_dir, sftp_retorno_dir, label, active, created_at, updated_at
`

type InsertPayerAccountParams struct {
	ID             pgtype.UUID
	BankCode       string
	Agency         string
	AccountNumber  string
	AccountDigit   string
	CertificateID  pgtype.UUID
	OauthClientID  string
	OauthSecretRef string
	SftpHost       pgtype.Text
	SftpUser       pgtype.Text
	SftpKeyRef     pgtype.Text
	SftpRemessaDir pgtype.Text
	SftpRetornoDir pgtype.Text
	Label          string
	Active         bool
}

func (q *Queries) InsertPayerAccount(ctx context.Context, arg InsertPayerAccountParams) (PayerAccount, error) {
	row := q.db.QueryRow(ctx, insertPayerAccount,
		arg.ID,
		arg.BankCode,
		arg.Agency,
		arg.AccountNumber,
		arg.AccountDigit,
		arg.CertificateID,
		arg.OauthClientID,
		arg.OauthSecretRef,
		arg.SftpHost,
		arg.SftpUser,
		arg.SftpKeyRef,
		arg.SftpRemessaDir,
		arg.SftpRetornoDir,
		arg.Label,
		arg.Active,
	)
	var i PayerAccount
	err := row.Scan(
		&i.ID,
		&i.BankCode,
		&i.Agency,
		&i.AccountNumber,
		&i.AccountDigit,
		&i.CertificateID,
		&i.OauthClientID,
		&i.OauthSecretRef,
		&i.SftpHost,
		&i.SftpUser,
		&i.SftpKeyRef,
		&i.SftpRemessaDir,
		&i.SftpRetornoDir,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayerAccounts = `-- name: ListPayerAccounts :many
SELECT id, bank_code, agency, account_number, account_digit, certificate_id, oauth_client_id, oauth_secret_ref, sftp_host, sftp_user, sftp_key_ref, sftp_remessa_dir, sftp_retorno_dir, label, active, created_at, updated_at FROM payer_accounts ORDER BY label
`

func (q *Queries) ListPayerAccounts(ctx context.Context) ([]PayerAccount, error) {
	rows, err := q.db.Query(ctx, listPayerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayerAccount{}
	for rows.Next() {
		var i PayerAccount
		if err := rows.Scan(
			&i.ID,
			&i.BankCode,
			&i.Agency,
			&i.AccountNumber,
			&i.AccountDigit,
			&i.CertificateID,
			&i.OauthClientID,
			&i.OauthSecretRef,
			&i.SftpHost,
			&i.SftpUser,
			&i.SftpKeyRef,
			&i.SftpRemessaDir,
			&i.SftpRetornoDir,
			&i.Label,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPayerAccountActive = `-- name: SetPayerAccountActive :exec
UPDATE payer_accounts SET active = $2, updated_at = now() WHERE id = $1
`

type SetPayerAccountActiveParams struct {
	ID     pgtype.UUID
	Active bool
}

func (q *Queries) SetPayerAccountActive(ctx context.Context, arg SetPayerAccountActiveParams) error {
	_, err := q.db.Exec(ctx, setPayerAccountActive, arg.ID, arg.Active)
	return err
}
