// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: payment_runs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPaymentToRun = `-- name: AttachPaymentToRun :one
INSERT INTO payment_run_items (run_id, payment_id, channel)
VALUES ($1, $2, $3)
RETURNING run_id, payment_id, channel, executed_at, settled_at
`

type AttachPaymentToRunParams struct {
	RunID     pgtype.UUID
	PaymentID pgtype.UUID
	Channel   string
}

func (q *Queries) AttachPaymentToRun(ctx context.Context, arg AttachPaymentToRunParams) (PaymentRunItem, error) {
	row := q.db.QueryRow(ctx, attachPaymentToRun, arg.RunID, arg.PaymentID, arg.Channel)
	var i PaymentRunItem
	err := row.Scan(
		&i.RunID,
		&i.PaymentID,
		&i.Channel,
		&i.ExecutedAt,
		&i.SettledAt,
	)
	return i, err
}

const detachPaymentFromRun = `-- name: DetachPaymentFromRun :exec
DELETE FROM payment_run_items WHERE run_id = $1 AND payment_id = $2
`

type DetachPaymentFromRunParams struct {
	RunID     pgtype.UUID
	PaymentID pgtype.UUID
}

func (q *Queries) DetachPaymentFromRun(ctx context.Context, arg DetachPaymentFromRunParams) error {
	_, err := q.db.Exec(ctx, detachPaymentFromRun, arg.RunID, arg.PaymentID)
	return err
}

const getPaymentRun = `-- name: GetPaymentRun :one
SELECT id, run_date, status, approved_at, approved_by, total_items, total_amount_cents, pix_count, ted_count, summary, created_at, closed_at, client_id FROM payment_runs WHERE id = $1
`

func (q *Queries) GetPaymentRun(ctx context.Context, id pgtype.UUID) (PaymentRun, error) {
	row := q.db.QueryRow(ctx, getPaymentRun, id)
	var i PaymentRun
	err := row.Scan(
		&i.ID,
		&i.RunDate,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TotalItems,
		&i.TotalAmountCents,
		&i.PixCount,
		&i.TedCount,
		&i.Summary,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClientID,
	)
	return i, err
}

const getPaymentRunForUpdate = `-- name: GetPaymentRunForUpdate :one
SELECT id, run_date, status, approved_at, approved_by, total_items, total_amount_cents, pix_count, ted_count, summary, created_at, closed_at, client_id FROM payment_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentRunForUpdate(ctx context.Context, id pgtype.UUID) (PaymentRun, error) {
	row := q.db.QueryRow(ctx, getPaymentRunForUpdate, id)
	var i PaymentRun
	err := row.Scan(
		&i.ID,
		&i.RunDate,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TotalItems,
		&i.TotalAmountCents,
		&i.PixCount,
		&i.TedCount,
		&i.Summary,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClientID,
	)
	return i, err
}

const insertPaymentRun = `-- name: InsertPaymentRun :one
INSERT INTO payment_runs (id, run_date, status)
VALUES ($1, $2, $3)
RETURNING id, run_date, status, approved_at, approved_by, total_items, total_amount_cents, pix_count, ted_count, summary, created_at, closed_at, client_id
`

type InsertPaymentRunParams struct {
	ID      pgtype.UUID
	RunDate pgtype.Date
	Status  string
}

func (q *Queries) InsertPaymentRun(ctx context.Context, arg InsertPaymentRunParams) (PaymentRun, error) {
	row := q.db.QueryRow(ctx, insertPaymentRun, arg.ID, arg.RunDate, arg.Status)
	var i PaymentRun
	err := row.Scan(
		&i.ID,
		&i.RunDate,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TotalItems,
		&i.TotalAmountCents,
		&i.PixCount,
		&i.TedCount,
		&i.Summary,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClientID,
	)
	return i, err
}

const listPaymentRunsByDate = `-- name: ListPaymentRunsByDate :many
SELECT id, run_date, status, approved_at, approved_by, total_items, total_amount_cents, pix_count, ted_count, summary, created_at, closed_at, client_id FROM payment_runs
WHERE run_date BETWEEN $1 AND $2
ORDER BY run_date DESC, created_at DESC
`

type ListPaymentRunsByDateParams struct {
	RunDate   pgtype.Date
	RunDate_2 pgtype.Date
}

func (q *Queries) ListPaymentRunsByDate(ctx context.Context, arg ListPaymentRunsByDateParams) ([]PaymentRun, error) {
	rows, err := q.db.Query(ctx, listPaymentRunsByDate, arg.RunDate, arg.RunDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentRun{}
	for rows.Next() {
		var i PaymentRun
		if err := rows.Scan(
			&i.ID,
			&i.RunDate,
			&i.Status,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.TotalItems,
			&i.TotalAmountCents,
			&i.PixCount,
			&i.TedCount,
			&i.Summary,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunItems = `-- name: ListRunItems :many
SELECT run_id, payment_id, channel, executed_at, settled_at FROM payment_run_items WHERE run_id = $1 ORDER BY payment_id
`

func (q *Queries) ListRunItems(ctx context.Context, runID pgtype.UUID) ([]PaymentRunItem, error) {
	rows, err := q.db.Query(ctx, listRunItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentRunItem{}
	for rows.Next() {
		var i PaymentRunItem
		if err := rows.Scan(
			&i.RunID,
			&i.PaymentID,
			&i.Channel,
			&i.ExecutedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunItemExecuted = `-- name: MarkRunItemExecuted :exec
UPDATE payment_run_items SET executed_at = now() WHERE run_id = $1 AND payment_id = $2
`

type MarkRunItemExecutedParams struct {
	RunID     pgtype.UUID
	PaymentID pgtype.UUID
}

func (q *Queries) MarkRunItemExecuted(ctx context.Context, arg MarkRunItemExecutedParams) error {
	_, err := q.db.Exec(ctx, markRunItemExecuted, arg.RunID, arg.PaymentID)
	return err
}

const markRunItemSettled = `-- name: MarkRunItemSettled :exec
UPDATE payment_run_items SET settled_at = now() WHERE run_id = $1 AND payment_id = $2
`

type MarkRunItemSettledParams struct {
	RunID     pgtype.UUID
	PaymentID pgtype.UUID
}

func (q *Queries) MarkRunItemSettled(ctx context.Context, arg MarkRunItemSettledParams) error {
	_, err := q.db.Exec(ctx, markRunItemSettled, arg.RunID, arg.PaymentID)
	return err
}

const updatePaymentRunCounters = `-- name: UpdatePaymentRunCounters :exec
UPDATE payment_runs
SET total_items = $2,
    total_amount_cents = $3,
    pix_count = $4,
    ted_count = $5
WHERE id = $1
`

type UpdatePaymentRunCountersParams struct {
	ID               pgtype.UUID
	TotalItems       int32
	TotalAmountCents int64
	PixCount         int32
	TedCount         int32
}

func (q *Queries) UpdatePaymentRunCounters(ctx context.Context, arg UpdatePaymentRunCountersParams) error {
	_, err := q.db.Exec(ctx, updatePaymentRunCounters,
		arg.ID,
		arg.TotalItems,
		arg.TotalAmountCents,
		arg.PixCount,
		arg.TedCount,
	)
	return err
}

const updatePaymentRunStatus = `-- name: UpdatePaymentRunStatus :one
UPDATE payment_runs
SET status = $2,
    approved_at = $3,
    approved_by = $4,
    closed_at = $5
WHERE id = $1
RETURNING id, run_date, status, approved_at, approved_by, total_items, total_amount_cents, pix_count, ted_count, summary, created_at, closed_at, client_id
`

type UpdatePaymentRunStatusParams struct {
	ID         pgtype.UUID
	Status     string
	ApprovedAt pgtype.Timestamptz
	ApprovedBy pgtype.Text
	ClosedAt   pgtype.Timestamptz
}

func (q *Queries) UpdatePaymentRunStatus(ctx context.Context, arg UpdatePaymentRunStatusParams) (PaymentRun, error) {
	row := q.db.QueryRow(ctx, updatePaymentRunStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedAt,
		arg.ApprovedBy,
		arg.ClosedAt,
	)
	var i PaymentRun
	err := row.Scan(
		&i.ID,
		&i.RunDate,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.TotalItems,
		&i.TotalAmountCents,
		&i.PixCount,
		&i.TedCount,
		&i.Summary,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClientID,
	)
	return i, err
}
