// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPaymentEvent = `-- name: InsertPaymentEvent :one
INSERT INTO payment_events (
    id, payment_id, from_status, to_status, actor, reason, payload, correlation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_id, at, from_status, to_status, actor, reason, payload, correlation_id
`

type InsertPaymentEventParams struct {
	ID            pgtype.UUID
	PaymentID     pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	Actor         string
	Reason        pgtype.Text
	Payload       []byte
	CorrelationID pgtype.Text
}

func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, insertPaymentEvent,
		arg.ID,
		arg.PaymentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
		arg.Reason,
		arg.Payload,
		arg.CorrelationID,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.At,
		&i.FromStatus,
		&i.ToStatus,
		&i.Actor,
		&i.Reason,
		&i.Payload,
		&i.CorrelationID,
	)
	return i, err
}

const listPaymentEventsForPayment = `-- name: ListPaymentEventsForPayment :many
SELECT id, payment_id, at, from_status, to_status, actor, reason, payload, correlation_id FROM payment_events
WHERE payment_id = $1
ORDER BY at ASC
`

func (q *Queries) ListPaymentEventsForPayment(ctx context.Context, paymentID pgtype.UUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listPaymentEventsForPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentEvent{}
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.At,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Reason,
			&i.Payload,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
