// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentsByStatus = `-- name: CountPaymentsByStatus :one
SELECT count(*) FROM payments WHERE status = $1
`

func (q *Queries) CountPaymentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.PayerAccountID,
		&i.BeneficiaryID,
		&i.BeneficiarySnapshot,
		&i.PayeeMethod,
		&i.Payee,
		&i.Description,
		&i.ScheduledFor,
		&i.IdempotencyKey,
		&i.BankReference,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.RescheduledFrom,
		&i.RescheduledReason,
		&i.OperatorNotes,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.PayerAccountID,
		&i.BeneficiaryID,
		&i.BeneficiarySnapshot,
		&i.PayeeMethod,
		&i.Payee,
		&i.Description,
		&i.ScheduledFor,
		&i.IdempotencyKey,
		&i.BankReference,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.RescheduledFrom,
		&i.RescheduledReason,
		&i.OperatorNotes,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.PayerAccountID,
		&i.BeneficiaryID,
		&i.BeneficiarySnapshot,
		&i.PayeeMethod,
		&i.Payee,
		&i.Description,
		&i.ScheduledFor,
		&i.IdempotencyKey,
		&i.BankReference,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.RescheduledFrom,
		&i.RescheduledReason,
		&i.OperatorNotes,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (
    id, external_id, type, status, amount_cents, currency,
    payer_account_id, beneficiary_id, beneficiary_snapshot,
    payee_method, payee, description, scheduled_for, idempotency_key,
    client_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes
`

type InsertPaymentParams struct {
	ID                  pgtype.UUID
	ExternalID          pgtype.Text
	Type                string
	Status              string
	AmountCents         int64
	Currency            string
	PayerAccountID      pgtype.UUID
	BeneficiaryID       pgtype.UUID
	BeneficiarySnapshot []byte
	PayeeMethod         string
	Payee               []byte
	Description         pgtype.Text
	ScheduledFor        pgtype.Date
	IdempotencyKey      string
	ClientID            pgtype.UUID
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.ExternalID,
		arg.Type,
		arg.Status,
		arg.AmountCents,
		arg.Currency,
		arg.PayerAccountID,
		arg.BeneficiaryID,
		arg.BeneficiarySnapshot,
		arg.PayeeMethod,
		arg.Payee,
		arg.Description,
		arg.ScheduledFor,
		arg.IdempotencyKey,
		arg.ClientID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.PayerAccountID,
		&i.BeneficiaryID,
		&i.BeneficiarySnapshot,
		&i.PayeeMethod,
		&i.Payee,
		&i.Description,
		&i.ScheduledFor,
		&i.IdempotencyKey,
		&i.BankReference,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.RescheduledFrom,
		&i.RescheduledReason,
		&i.OperatorNotes,
	)
	return i, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPaymentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listAllPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.PayerAccountID,
			&i.BeneficiaryID,
			&i.BeneficiarySnapshot,
			&i.PayeeMethod,
			&i.Payee,
			&i.Description,
			&i.ScheduledFor,
			&i.IdempotencyKey,
			&i.BankReference,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.RescheduledFrom,
			&i.RescheduledReason,
			&i.OperatorNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByClientAndStatus = `-- name: ListPaymentsByClientAndStatus :many
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments
WHERE client_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentsByClientAndStatusParams struct {
	ClientID pgtype.UUID
	Status   string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPaymentsByClientAndStatus(ctx context.Context, arg ListPaymentsByClientAndStatusParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByClientAndStatus,
		arg.ClientID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.PayerAccountID,
			&i.BeneficiaryID,
			&i.BeneficiarySnapshot,
			&i.PayeeMethod,
			&i.Payee,
			&i.Description,
			&i.ScheduledFor,
			&i.IdempotencyKey,
			&i.BankReference,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.RescheduledFrom,
			&i.RescheduledReason,
			&i.OperatorNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStatus = `-- name: ListPaymentsByStatus :many
SELECT id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes FROM payments
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.PayerAccountID,
			&i.BeneficiaryID,
			&i.BeneficiarySnapshot,
			&i.PayeeMethod,
			&i.Payee,
			&i.Description,
			&i.ScheduledFor,
			&i.IdempotencyKey,
			&i.BankReference,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.RescheduledFrom,
			&i.RescheduledReason,
			&i.OperatorNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForRun = `-- name: ListPaymentsForRun :many
SELECT p.id, p.external_id, p.type, p.status, p.amount_cents, p.currency, p.payer_account_id, p.beneficiary_id, p.beneficiary_snapshot, p.payee_method, p.payee, p.description, p.scheduled_for, p.idempotency_key, p.bank_reference, p.rejection_reason, p.created_at, p.updated_at, p.client_id, p.rescheduled_from, p.rescheduled_reason, p.operator_notes
FROM payments p
JOIN payment_run_items i ON i.payment_id = p.id
WHERE i.run_id = $1
ORDER BY p.created_at
`

func (q *Queries) ListPaymentsForRun(ctx context.Context, runID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.PayerAccountID,
			&i.BeneficiaryID,
			&i.BeneficiarySnapshot,
			&i.PayeeMethod,
			&i.Payee,
			&i.Description,
			&i.ScheduledFor,
			&i.IdempotencyKey,
			&i.BankReference,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
			&i.RescheduledFrom,
			&i.RescheduledReason,
			&i.OperatorNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = now(), bank_reference = COALESCE($3, bank_reference),
    rejection_reason = COALESCE($4, rejection_reason)
WHERE id = $1
RETURNING id, external_id, type, status, amount_cents, currency, payer_account_id, beneficiary_id, beneficiary_snapshot, payee_method, payee, description, scheduled_for, idempotency_key, bank_reference, rejection_reason, created_at, updated_at, client_id, rescheduled_from, rescheduled_reason, operator_notes
`

type UpdatePaymentStatusParams struct {
	ID              pgtype.UUID
	Status          string
	BankReference   pgtype.Text
	RejectionReason pgtype.Text
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.BankReference,
		arg.RejectionReason,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Type,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.PayerAccountID,
		&i.BeneficiaryID,
		&i.BeneficiarySnapshot,
		&i.PayeeMethod,
		&i.Payee,
		&i.Description,
		&i.ScheduledFor,
		&i.IdempotencyKey,
		&i.BankReference,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.RescheduledFrom,
		&i.RescheduledReason,
		&i.OperatorNotes,
	)
	return i, err
}
