// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachPaymentToRun(ctx context.Context, arg AttachPaymentToRunParams) (PaymentRunItem, error)
	CheckBlacklist(ctx context.Context, arg CheckBlacklistParams) ([]BlacklistEntry, error)
	CountActiveBankConnections(ctx context.Context, clientID pgtype.UUID) (int64, error)
	CountPaymentsByStatus(ctx context.Context, status string) (int64, error)
	DeactivateBlacklistEntry(ctx context.Context, id pgtype.UUID) error
	DeleteBankCertificate(ctx context.Context, id pgtype.UUID) error
	DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) error
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	DetachPaymentFromRun(ctx context.Context, arg DetachPaymentFromRunParams) error
	FindDuplicatePayments(ctx context.Context, arg FindDuplicatePaymentsParams) ([]Payment, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetBankCertificate(ctx context.Context, id pgtype.UUID) (BankCertificate, error)
	GetBankConnection(ctx context.Context, arg GetBankConnectionParams) (BankConnection, error)
	GetBankConnectionByBank(ctx context.Context, arg GetBankConnectionByBankParams) (BankConnection, error)
	GetBeneficiary(ctx context.Context, id pgtype.UUID) (Beneficiary, error)
	GetBeneficiaryByDocument(ctx context.Context, documentNumber string) (Beneficiary, error)
	GetClient(ctx context.Context, id pgtype.UUID) (Client, error)
	GetClientByDocument(ctx context.Context, documentNumber string) (Client, error)
	GetClientBySlug(ctx context.Context, slug pgtype.Text) (Client, error)
	GetClientLimit(ctx context.Context, clientID pgtype.UUID) (ClientLimit, error)
	GetCnabFile(ctx context.Context, id pgtype.UUID) (CnabFile, error)
	GetCnabFileByHash(ctx context.Context, fileHash string) (CnabFile, error)
	GetDuplicateRule(ctx context.Context, clientID pgtype.UUID) (DuplicateRule, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetPayerAccount(ctx context.Context, id pgtype.UUID) (PayerAccount, error)
	GetPayerAccountByLabel(ctx context.Context, label string) (PayerAccount, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetPaymentForUpdate(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentRun(ctx context.Context, id pgtype.UUID) (PaymentRun, error)
	GetPaymentRunForUpdate(ctx context.Context, id pgtype.UUID) (PaymentRun, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWebhookDelivery(ctx context.Context, id pgtype.UUID) (WebhookDelivery, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error)
	InsertBankCertificate(ctx context.Context, arg InsertBankCertificateParams) (BankCertificate, error)
	InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error)
	InsertBeneficiary(ctx context.Context, arg InsertBeneficiaryParams) (Beneficiary, error)
	InsertBeneficiaryBankAccount(ctx context.Context, arg InsertBeneficiaryBankAccountParams) (BeneficiaryBankAccount, error)
	InsertBeneficiaryPixKey(ctx context.Context, arg InsertBeneficiaryPixKeyParams) (BeneficiaryPixKey, error)
	InsertBlacklistEntry(ctx context.Context, arg InsertBlacklistEntryParams) (BlacklistEntry, error)
	InsertClient(ctx context.Context, arg InsertClientParams) (Client, error)
	InsertClientLimit(ctx context.Context, arg InsertClientLimitParams) (ClientLimit, error)
	InsertCnabFile(ctx context.Context, arg InsertCnabFileParams) (CnabFile, error)
	InsertDuplicateRule(ctx context.Context, arg InsertDuplicateRuleParams) (DuplicateRule, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	InsertPayerAccount(ctx context.Context, arg InsertPayerAccountParams) (PayerAccount, error)
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (PaymentEvent, error)
	InsertPaymentRun(ctx context.Context, arg InsertPaymentRunParams) (PaymentRun, error)
	InsertPrevalidationResult(ctx context.Context, arg InsertPrevalidationResultParams) (PrevalidationResult, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error)
	LatestPrevalidation(ctx context.Context, arg LatestPrevalidationParams) (PrevalidationResult, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error)
	ListAllUsers(ctx context.Context) ([]User, error)
	ListApiKeys(ctx context.Context) ([]ApiKey, error)
	ListApiKeysByClient(ctx context.Context, clientID pgtype.UUID) ([]ApiKey, error)
	ListBankCertificatesByBank(ctx context.Context, arg ListBankCertificatesByBankParams) ([]BankCertificate, error)
	ListBankConnections(ctx context.Context, clientID pgtype.UUID) ([]BankConnection, error)
	ListBeneficiaries(ctx context.Context, arg ListBeneficiariesParams) ([]Beneficiary, error)
	ListBeneficiaryBankAccounts(ctx context.Context, beneficiaryID pgtype.UUID) ([]BeneficiaryBankAccount, error)
	ListBeneficiaryPixKeys(ctx context.Context, beneficiaryID pgtype.UUID) ([]BeneficiaryPixKey, error)
	ListBlacklistByClient(ctx context.Context, clientID pgtype.UUID) ([]BlacklistEntry, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListCnabFilesByRun(ctx context.Context, runID pgtype.UUID) ([]CnabFile, error)
	ListCnabFilesByStatus(ctx context.Context, status string) ([]CnabFile, error)
	ListPayerAccounts(ctx context.Context) ([]PayerAccount, error)
	ListPaymentEventsForPayment(ctx context.Context, paymentID pgtype.UUID) ([]PaymentEvent, error)
	ListPaymentRunsByDate(ctx context.Context, arg ListPaymentRunsByDateParams) ([]PaymentRun, error)
	ListPaymentsByClientAndStatus(ctx context.Context, arg ListPaymentsByClientAndStatusParams) ([]Payment, error)
	ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]Payment, error)
	ListPaymentsForRun(ctx context.Context, runID pgtype.UUID) ([]Payment, error)
	ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	ListPrevalidationsByPayment(ctx context.Context, paymentID pgtype.UUID) ([]PrevalidationResult, error)
	ListRunItems(ctx context.Context, runID pgtype.UUID) ([]PaymentRunItem, error)
	ListUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]User, error)
	ListWebhookDeliveriesByPayment(ctx context.Context, paymentID pgtype.UUID) ([]WebhookDelivery, error)
	MarkRunItemExecuted(ctx context.Context, arg MarkRunItemExecutedParams) error
	MarkRunItemSettled(ctx context.Context, arg MarkRunItemSettledParams) error
	RevokeApiKey(ctx context.Context, id pgtype.UUID) error
	SetClientActive(ctx context.Context, arg SetClientActiveParams) error
	SetOnboardingCompleted(ctx context.Context, id pgtype.UUID) error
	SetPayerAccountActive(ctx context.Context, arg SetPayerAccountActiveParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SumPaymentsMonthByClient(ctx context.Context, clientID pgtype.UUID) (int64, error)
	SumPaymentsTodayByClient(ctx context.Context, clientID pgtype.UUID) (int64, error)
	TouchApiKey(ctx context.Context, id pgtype.UUID) error
	TouchUserLogin(ctx context.Context, id pgtype.UUID) error
	UpdateBankConnectionCredentials(ctx context.Context, arg UpdateBankConnectionCredentialsParams) error
	UpdateBankConnectionStatus(ctx context.Context, arg UpdateBankConnectionStatusParams) error
	UpdateClientBranding(ctx context.Context, arg UpdateClientBrandingParams) error
	UpdateClientLimit(ctx context.Context, arg UpdateClientLimitParams) error
	UpdateClientWebhook(ctx context.Context, arg UpdateClientWebhookParams) error
	UpdateCnabFileStatus(ctx context.Context, arg UpdateCnabFileStatusParams) (CnabFile, error)
	UpdatePaymentRunCounters(ctx context.Context, arg UpdatePaymentRunCountersParams) error
	UpdatePaymentRunStatus(ctx context.Context, arg UpdatePaymentRunStatusParams) (PaymentRun, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error
}

var _ Querier = (*Queries)(nil)
