// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbgen

import (
	"context"
)

type Querier interface {
	GetSchemaMetadataValue(ctx context.Context, key string) (string, error)
}

var _ Querier = (*Queries)(nil)
