// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, client_id, email, password_hash, name, role, active, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, client_id, email, password_hash, name, role, active, last_login_at, created_at, updated_at FROM users WHERE email = $1 AND active = TRUE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, client_id, email, password_hash, name, role, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, email, password_hash, name, role, active, last_login_at, created_at, updated_at
`

type InsertUserParams struct {
	ID           pgtype.UUID
	ClientID     pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	Active       bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.ClientID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, client_id, email, password_hash, name, role, active, last_login_at, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByClient = `-- name: ListUsersByClient :many
SELECT id, client_id, email, password_hash, name, role, active, last_login_at, created_at, updated_at FROM users WHERE client_id = $1 ORDER BY name
`

func (q *Queries) ListUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID     pgtype.UUID
	Active bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
