// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_deliveries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, client_id, payment_id, event_type, payload, status, response_status, response_body, attempts, last_attempt_at, created_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id pgtype.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PaymentID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id, client_id, payment_id, event_type, payload, status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, payment_id, event_type, payload, status, response_status, response_body, attempts, last_attempt_at, created_at
`

type InsertWebhookDeliveryParams struct {
	ID        pgtype.UUID
	ClientID  pgtype.UUID
	PaymentID pgtype.UUID
	EventType string
	Payload   []byte
	Status    string
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.ID,
		arg.ClientID,
		arg.PaymentID,
		arg.EventType,
		arg.Payload,
		arg.Status,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PaymentID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingWebhookDeliveries = `-- name: ListPendingWebhookDeliveries :many
SELECT id, client_id, payment_id, event_type, payload, status, response_status, response_body, attempts, last_attempt_at, created_at FROM webhook_deliveries
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.PaymentID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByPayment = `-- name: ListWebhookDeliveriesByPayment :many
SELECT id, client_id, payment_id, event_type, payload, status, response_status, response_body, attempts, last_attempt_at, created_at FROM webhook_deliveries
WHERE payment_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookDeliveriesByPayment(ctx context.Context, paymentID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.PaymentID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDeliveryStatus = `-- name: UpdateWebhookDeliveryStatus :exec
UPDATE webhook_deliveries
SET status = $2,
    response_status = $3,
    response_body = $4,
    attempts = attempts + 1,
    last_attempt_at = now()
WHERE id = $1
`

type UpdateWebhookDeliveryStatusParams struct {
	ID             pgtype.UUID
	Status         string
	ResponseStatus pgtype.Int4
	ResponseBody   pgtype.Text
}

func (q *Queries) UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}
